name: "Ollama"
description: "Run Ollama server as a Home Assistant add-on"
version: "0.0.1"
slug: "ollama"
init: false

arch:
  - aarch64
  - amd64

startup: services
ports:
  11434/tcp: 11434

webui: "http://[HOST]:[PORT:11434]"

options:
  model: ""
schema:
  model: str