name: "Ollama Service (Local)"
version: "0.1.0"
slug: "ollama_service"

description: "Runs Ollama locally"

arch:
  - aarch64

startup: services
init: false

ports:
  11434/tcp: 11434

map:
  - addon_config:rw
